### ISSUE TITLE
Tổng quát về phần mềm

### ISSUE THREAD

**Issue by quandapro** [quandapro/SE03-group06#1]
- Lưu trữ hình ảnh võng mạc

- Viewer hiển thị hình ảnh võng mạc (hiển thị hình ảnh, kích cỡ, zoom, công cụ crop)

- Hỗ trợ chẩn đoán bệnh võng mạc tiểu đường (Trả ra kết quả là xác suất bị bệnh võng mạc tiểu đường, VD: 60%) (Ứng dụng deep learning)

**Comment by HieuBatman** [comment]
- Giao diện sơ bộ bao gồm:
+ Giao diện đăng nhập.
+ Giao diện hiển thị cho người dùng (bao gồm: ảnh, tên, ...).
- Cơ sở dữ liệu bao gồm:
+ Thông tin đăng nhập.
+ Dữ liệu lưu trữ (ảnh, thời gian chỉnh sửa, ...).

**Comment by HieuBatman** [comment]
Sẽ có 2 phần chính: Front-End và Back-End
Phần Front-end sẽ làm về giao diện đăng nhập,đăng ký,  giao diện người dùng. Sẽ sử dụng giao diện web để hiển thị.
Phần Back-end sẽ liên quan đến quản lý cơ sở dữ liệu quản lý user, hình ảnh, lưu trữ file, xử lý truy vấn,...
Tôi sẽ nhận về phần front-end.

**Comment by KkEditor** [comment]
- hỗ trợ hiển thị ảnh dưới nhiều filter khác nhau, khoảng từ 4-6 filter.
- có option chuyển đổi giữa các filter và so sánh ảnh qua các filter với nhau
- import, export tùy ý các ảnh qua filter

**Comment by quandapro** [comment]
Hmm thêm cái filter để giúp doctor nhận diện vùng tổn thương tốt hơn cũng hay đấy

**Comment by KkEditor** [comment]
okay thì để cho thêm 1 tính năng đấy vào, sẽ crop vùng tổn thương

**Comment by KkEditor** [comment]
phần giao diện cũng nên upload code lên dần đi, để sau lại không kịp

**Comment by HieuBatman** [comment]
Tuần này sẽ có giao diện web

**Comment by HieuBatman** [comment]
Trong tuần này sẽ có giao diện
