### ISSUE TITLE
Giao diện bác sĩ

### ISSUE THREAD

**Issue by Truong-Giang** [quandapro/SE03-group06#11]
Trước thứ 6 có giao diện cơ bản cho bác sĩ, mọi người xem ngoài các tính năng Nhật Hiếu đã nêu ra còn cần thêm gì để mình thêm tiếp vào.

**Comment by quandapro** [comment]
Ơ thêm vào chưa?

**Comment by quandapro** [comment]
Phải nhìn giao diện cơ bản rồi mới bổ sung được chứ

**Comment by HieuBatman** [comment]
Làm đi, mấy cái thứ 6 rồi!

**Comment by quandapro** [comment]
Thế cuối cùng có làm ko? Ko thì t với Nhạt làm!
