### ISSUE TITLE
HomePage + Login

### ISSUE THREAD

**Issue by HieuBatman** [quandapro/SE03-group06#13]
Đã xong giao diện trang chủ và giao diện đăng nhập.
Còn : 
+Giao diện admin(xem, thêm, xóa, sửa data).
+Giao diện bác sỹ(xem ảnh, chuẩn đoán bệnh).

**Comment by HieuBatman** [comment]
Các bạn xem xét phần xử lý dữ liệu users, tìm hiểu cái flask hoặc django.

**Comment by KkEditor** [comment]
ông điều chình thanh navbar nhỏ lại nhé, đồng thời các element trong navbả đang không hoạt động

**Comment by HieuBatman** [comment]
Các element trong này đang đa số là tĩnh (do chưa hoàn thiện xong các gd chức năng khác ).
Còn về sau ô thắc mắc hay yêu cầu phần nào nữa thì viết tên class giúp tôi với.
