### ISSUE TITLE
Chức năng của admin và guest

### ISSUE THREAD

**Issue by KkEditor** [quandapro/SE03-group06#16]
hiện tại đang chia ra 2 thẩm quyền: admin và guest. Mỗi quyền có chức năng gì và ảnh hưởng đến nhau ntn?

**Comment by quandapro** [comment]
Admin và bác sĩ chứ. Admin chỉ có quyền thêm, đổi pass, xóa bác sĩ. Bác sĩ có quyền sử dụng viewer, xem ảnh, thao tác với ảnh,...

**Comment by KkEditor** [comment]
sao k để là ai cũng có thể thao tác với ảnh, nhưng muốn lưu lại ảnh trên galery và so sánh các ảnh với nhau thì sẽ cần account
nếu k có acc thì chỉ xử lý ảnh trong phiên làm việc đấy thôi, reset browser sẽ mất

**Comment by HieuBatman** [comment]
nên là admin chỉ có tác vụ quản lý người dùng thôi, chỉ có bác sỹ mới có quyền chuẩn đoán bệnh.
