### ISSUE TITLE
Tài liệu thiết kế web

### ISSUE THREAD

**Issue by HieuBatman** [quandapro/SE03-group06#17]
- T đọc cái demo kk gửi rồi, nhưng cái homepage đấy tôi nghĩ chỉ đơn giản là giới thiệu về ứng dụng của project và công việc của những người trong nhóm.
- Cái phần chức năng thì homepage thì nên chỉ có chức năng duy nhất là login.
Tùy theo tài khoản đó là gì (phụ thuộc vào password của acc, vd: nếu pass có số 0 ở đầu thì là admin, còn lại là bác sỹ) thì mới dẫn đến 2 giao diện sau:
+ Nếu là admin thì giao diện sẽ có: thêm bác sỹ, thêm admin(chung 1 giao diện users); xem thông tin người dùng(cái này chỉ có admin mới xem được, nên chỉ cần 1 trang html đơn giản để view ra toàn bộ thông tin(như họ tên, chức vụ,....)) và xóa account.
+ Nếu là bác sỹ thì chỉ dẫn đến 1 trang khám bệnh(cho phép là việc trên ảnh + chuẩn đoán bệnh).
KK trong quá trình làm flask nếu muốn thay đổi giao diện sao cho dễ code thì cứ thoải mái, sau đó commit lên t chỉnh lại cũng được.
- Hiện tại nhóm còn phần nữa là database(thiết kế + tạo dữ liệu), hôm trước quân có nhận nhưng hiện tại quân đang bận đi thi nên kk nếu cân được thì confirm lại, không thì cuối tuần này sẽ chia việc lại cái đấy.

**Comment by KkEditor** [comment]
homepage và landing page là khác nhau nhé
