### ISSUE TITLE
Update giao diện

### ISSUE THREAD

**Issue by HieuBatman** [quandapro/SE03-group06#8]
còn 2 giao diện chính:
-Admin
-Doctor
Giao diện Doctor sẽ giao cho Giang nhé! Bao gồm: Xem ảnh, tên bệnh nhân, hồ sơ bệnh, và chuẩn đoán bệnh.
Tôi sẽ làm giao diện Admin

**Comment by quandapro** [comment]
Cái viewer nhớ thêm phần filters, crop, zoom. Nếu không xử lý được tại front end thì chỉ cần gửi request cho backend xử lý và chờ response là ok.
